sudo: required
services:
  - docker

before_install:
  - docker build -t erwin09/erwinsweb -f Dockerfile.dev .

script:
  - docker run erwin09/erwinsweb npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "erwinsweb"
  env: "Erwinsweb-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-207398959169"
  bucket_path: "erwinsweb"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

